version: "3.7"

services:
  app1:
    image: test_go_app
    networks:
      - "app_net"
  app2:
    image: test_go_app
    networks:
      - "app_net"

  app3:
    image: test_go_app
    networks:
      - "app_net"
  ngnix:
    image: nginx:latest
    ports:
      - "9090:9090"
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - "app_net"
    depends_on:
      - app1
      - app2
      - app3
networks:
  app_net:
